core/accounts/urls.py
from django.urls import path
#from accounts.views import *
from accounts.views import * 


app_name = 'accounts'

urlpatterns = [
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogOut.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='signup'),
    path('changepassword/',UserPasswordResetView.as_view(),name='changepassword'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

core/blog/urls.py
from django.urls import path
from blog.views import * 
from django.contrib.sitemaps.views import sitemap
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('',blog_view, name ='blog'),
    path('post-<int:post_id>/<slug:post_slug>/',Blog_Details_View.as_view(), name ='blog-details'),
    path('category/<str:cat_name>/',blog_view, name ='category'),
    path('tag/<str:tag_name>/',blog_view, name ='tag'),
    path('author/<str:author_username>/',blog_view,name ='author'),
    path('search/',Searchview.as_view(),name ='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('like/',LikePost_View, name ='like'),
    ]
 

core/mysite/urls.py
from django.contrib import admin 
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}
     
urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('website.urls')),
        path('blog/',include('blog.urls')),  
        path('captcha/', include('captcha.urls')),
        path('accounts/',include('accounts.urls')),
        path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
        path('robots.txt', include('robots.urls')),
        path("__debug__/", include("debug_toolbar.urls")),
        path('summernote/', include('django_summernote.urls')),
    ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('resume', resume_view, name='resume'),
    path('skill', skill_view, name='skill'),
    path('', coming_view, name='coming'),
    ]

core/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from io import BytesIO
from django.core.files import File
from taggit.managers import TaggableManager
from mysite.tools import UploadToPathAndRename
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils.text import slugify

def get_image_field(self):
    output = []
    for k, v in self.__dict__.items():
        if isinstance(v, ImageFieldFile):
            output.append(k)
    return output


class MainModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name=_("create date"))
    modify_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name=_("modify date"))
    is_active = models.BooleanField(default=True, verbose_name=_("is active"))

    def save(self, *args, **kwargs):
        image_fields = get_image_field(self)
        if image_fields:
            for i in image_fields:
                if hasattr(self, i) and isinstance(getattr(self, i), ImageFieldFile):
                    image = Image.open(getattr(self, i).file)
                    image_io = BytesIO()
                    image_extension = getattr(self, i).name.rpartition(".")[-1].upper()
                    image_extension = "JPEG" if image_extension == "JPG" else image_extension
                    image.save(image_io, image_extension, quality=60)
                    new_image = File(image_io, name=getattr(self, i).name)
                    setattr(self, i, new_image)
        self.full_clean()
        super().save(*args, **kwargs)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
# Create your models here.

class Post(MainModel): 
    image = models.ImageField(upload_to=UploadToPathAndRename("blog"),default='blog/defualt.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True, related_name='posts_author')
    title = models.CharField(max_length=255)
    slug = models.SlugField(null=True,blank=True,unique=True)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    login_require = models.BooleanField(default=False)
    
    def save (self, force_insert = False, force_update=False, using=None,update_fields=None):
        self.slug = slugify(self.title)
        super(Post,self).save()
        
    def image_tag(self):
        return mark_safe(f'<img src="{settings.MEDIA_URL}{self.image}" height="50" />')
    image_tag.allow_tags = True
    image_tag.short_description = "---"
    
    def get_absolute_url(self):
       return reverse("blog:blog-details", args=(self.id, self.slug))
    def __str__(self):
        return self.title
    
    def like_count(self):
        return self.upost.count()
   
    def user_can_like(self, user):
        user_like = user.uvote.filter(post = self)
        if user_like.exists():
            return True
        return False
    
class Comment(MainModel):
    post = models.ForeignKey(Post,on_delete = models.CASCADE, related_name="comments",null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments",null=True,blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name="replies",null=True,blank=True)
    message = models.TextField()
    approach = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True) 
    class Meta:
        ordering = ('created_date',)
  
    def __str__(self):
        return self.message[:20]
    
class VoteUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='upost')
    
    def __str__(self):
        return f'{self.user} --> like this post-->  {self.post.slug}' 
    
class PostImage(models.Model):
    product = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=UploadToPathAndRename("blog"),default='blog/defualt.jpg')

    def __unicode__(self):
        return self.product.title

    def __str__(self):
        return self.product.title

  

core/blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm): 
    captcha = CaptchaField() 
    class Meta:
        model = Comment
        fields = ['message',]

core/blog/views.py
from typing import Any
from django import http
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post,PostImage
from django.utils import timezone
from blog.forms import  CommentForm
from blog.models import Post,Comment,VoteUser
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from taggit.models import Tag
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def blog_view(request,**kwargs):
    posts = Post.objects.filter(status=1,published_date__lte = timezone.now())
    if kwargs.get('cat_name') != None:
        cat = kwargs.get('cat_name')
        posts = posts.filter(category__name = cat.replace("-", " "))
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__slug__in = [kwargs['tag_name']])
        
    posts = Paginator(posts,2)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    tags = Tag.objects.all()
    context = {'posts':posts,'tags':tags} 
    return render (request , 'blog/blog-home.html',context)

def LikePost_View(request):
    post_id = request.GET['post_id']
    post = get_object_or_404(Post, id = post_id)
    like = VoteUser.objects.filter(post= post, user= request.user)
    data = ("item successfully added to cart")
    if like.exists():
        like.delete()
        post.save()
        return JsonResponse({"error": data})
    else:
        VoteUser.objects.create(post= post,  user= request.user)           
        return JsonResponse({"success": data})
        

class Blog_Details_View(View):
    form_class = CommentForm
    template_name = 'blog/blog-details.html'
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,pk=kwargs['post_id'],slug= kwargs['post_slug'])
        self.images_instance = PostImage.objects.filter(product_id =kwargs['post_id'])
        self.comment_instance = Comment.objects.filter(approach=True,parent=None,post=self.post_instance.id).order_by('created_date')        
        #self.reply_instance = Comment.objects.filter(approach=True,parent__isnull=False,post=self.post_instance.id).order_by('created_date')        
        return super().setup(request, *args, **kwargs)
    def get(self,request,*args, **kwargs):
        form = self.form_class()
        if not self.post_instance.login_require or request.user.is_authenticated:
            print('salaam')
            can_like = False
            if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
                can_like = True
            self.post_instance.counted_views+=1
            self.post_instance.save()
            form = self.form_class()
            content = {'post':self.post_instance,'form':form,'can_like':can_like,'images':self.images_instance,'comments': self.comment_instance}#,"replyes":self.reply_inctance,
            return render (request , self.template_name,content)
        else:
            return redirect("/accounts/login?next="+request.path)
    def post(self,request,*args, **kwargs):
        parent_id = request.POST.get('parent_id')
        form = self.form_class(request.POST)        
        if form.is_valid():
            endcomment = form.save(commit=False)
            endcomment.post = self.post_instance
            if request.user.is_authenticated:
                endcomment.user = request.user
            else:
                endcomment.user = None
            endcomment.parent_id = parent_id
            endcomment.save()
            if parent_id:
                messages.success(request,'Thanks . Your Reply has been received.','success')
            else:
                messages.success(request,'Thanks . Your comment has been received.','success')
        else:
            messages.error(request,'Please inter correct pattern .','error')
        return redirect('blog:blog-details', self.post_instance.id, self.post_instance.slug) 
      


class Searchview(View):
    def get(self,request):
        posts = Post.objects.filter(status=1)
        q = request.GET.get('q')
        posts = posts.filter(content__icontains=q)
        posts = Paginator(posts,2)
        try:
            page_number = request.GET.get('page')
            posts = posts.get_page(page_number)
        except PageNotAnInteger:
            posts = posts.get_page(1)
        except EmptyPage:
            posts = posts.get_page(1)
        context = {'posts':posts}
        return render (request , 'blog/blog-home.html',context)



        

core/templates/blog/includes/footer.html
{% load static %}

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="social-icons">
          <li><a href="{{ myinformations.whatsapp }}">Whatsapp</a></li>
          <li><a href="{{ myinformations.telegram }}">Telegram</a></li>
          <li><a href="{{ myinformations.instagram }}">Instagram</a></li>
          <li><a href="{{ myinformations.linkedin }}">Linkedin</a></li>
          <li><a href="mailto:{{ myinformations.email }}">Email</a></li>
        </ul>
      </div>
      <div class="col-lg-12">
        <div class="copyright-text">
          <p>Copyright 2020 Stand Blog Co.
                
             | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

core/templates/blog/includes/footer_references.html
{% load static %}
{% load compress %}
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %} "></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
{% compress js %}
<!-- Bootstrap core JavaScript -->
<!-- Additional Scripts -->
<script src="{% static 'blog/assets/js/custom.js' %} "></script>
<script src="{% static 'blog/assets/js/owl.js' %} "></script>
<script src="{% static 'blog/assets/js/slick.js' %} "></script>
<script src="{% static 'blog/assets/js/isotope.js' %} "></script>
<script src="{% static 'blog/assets/js/accordions.js' %} "></script>
<script type="text/javascript" src="{% static 'blog/assets/js/toastr.min.js' %}"></script>  
<script src="{% static 'blog/assets/js/main.js' %}"></script>
{% endcompress %}

<script language = "text/Javascript"> 
  cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
  function clearField(t){                   //declaring the array outside of the
  if(! cleared[t.id]){                      // function makes it static and global
      cleared[t.id] = 1;  // you could use true and false, but that's more typing
      t.value='';         // with more chance of typos
      t.style.color='#fff';
      }
  }
</script>

  <script>
  {% if messages %}
  document.addEventListener("DOMContentLoaded", function(event) {
      toastr.options = { "closeButton": true, "debug": false, "newestOnTop": true,
          "progressBar": false, "positionClass": "toast-top-right", "preventDuplicates": true,
          "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000",
          "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear",
          "showMethod": "fadeIn", "hideMethod": "fadeOut" };
      {% autoescape off %}
          {% for msg in messages %}
              toastr.{{ msg.level_tag }}("{{ msg }}");
          {% endfor %}
      {% endautoescape %}
  });
{% endif %}
</script>

  <!-- Template Main JS File -->
  
  <script>
    $(function() {

      // Add refresh button after field (this can be done in the template as well)
      $('img.captcha').after(
              $('<a href="#void" class="captcha-refresh" > <i class="fa fa-refresh" style="font-size:24px"></i> </a>')
              );
  
      // Click-handler for the refresh-link
      $('.captcha-refresh').click(function(){
          var $form = $(this).parents('form');
          var url = location.protocol + "//" + window.location.hostname + ":"
                    + location.port + "/captcha/refresh/";
  
          // Make the AJAX-call
          $.getJSON(url, {}, function(json) {
              $form.find('input[name="captcha_0"]').val(json.key);
              $form.find('img.captcha').attr('src', json.image_url);
          });
  
          return false;
      });

});

  </script>

  <script type="text/javascript">
  $('.likebutton').click(function(){
    var catid;
    var element = document.getElementById("like")
    var count = document.getElementById("count")
    var count1 = document.getElementById("count1")
  catid = $(this).attr("data-catid");

  $.ajax(
  {
      type:"GET",
      url: "{% url 'blog:like' %}",
      data:{
               post_id: catid
      },
      success: function( data ) {
        if (data["error"]) {
            toastr.error("you disliked this post")
            element.className = "likebutton fa fa-heart-o"
            count.innerText = Number(count.innerText) - 1
            count1.innerText = Number(count1.innerText) - 1
            
        }else if (data["success"]) {
        toastr.success("you liked this post") 
        element.className = "likebutton fa fa-heart"
        count.innerText = Number(count.innerText) + 1
        count1.innerText = Number(count1.innerText) + 1
             
      }
    }
   })
});
</script>

core/templates/blog/includes/head_references.html
{% load static %}
{% load compress %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<!-- Bootstrap core CSS -->
{% compress css %}
<<link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static 'blog/assets/css/toastr.min.css' %}" media="all">
<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'blog/assets/css/fontawesome.css' %} ">
<link rel="stylesheet" href="{% static 'blog/assets/css/templatemo-stand-blog.css' %} ">
<link rel="stylesheet" href="{% static 'blog/assets/css/owl.css' %} ">
{% endcompress %}
<!--% static 'blog/

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->

core/templates/blog/includes/header.html
{% load static %}

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'website:index' %}"><h2>Home<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item {% if request.resolver_match.url_name == 'blog' %}active{% endif %}">
                <a class="nav-link" href="{% url 'blog:blog' %}">Stand Blog
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link">{{ request.user.username}}</a>
                <a class="nav-link" href="{% url 'accounts:logout' %}">LogOut</a>
                {% else %}
              </li>
              <li class="nav-item  ">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">signup</a>
              </li>
              {% endif %}
             
            </ul>
          </div>
        </div>
      </nav>
    </header>