core/accounts/urls.py
from django.urls import path
#from accounts.views import *
from accounts.views import * 


app_name = 'accounts'

urlpatterns = [
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogOut.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='signup'),
    path('changepassword/',UserPasswordResetView.as_view(),name='changepassword'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

core/blog/urls.py
from django.urls import path
from blog.views import * 
from django.contrib.sitemaps.views import sitemap
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('',blog_view, name ='blog'),
    path('post-<int:post_id>/<slug:post_slug>/',Blog_Details_View.as_view(), name ='blog-details'),
    path('category/<str:cat_name>/',blog_view, name ='category'),
    path('tag/<str:tag_name>/',blog_view, name ='tag'),
    path('author/<str:author_username>/',blog_view,name ='author'),
    path('search/',Searchview.as_view(),name ='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('like/',LikePost_View, name ='like'),
    ]
 

core/mysite/urls.py
from django.contrib import admin 
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}
     
urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('website.urls')),
        path('blog/',include('blog.urls')),  
        path('captcha/', include('captcha.urls')),
        path('accounts/',include('accounts.urls')),
        path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
        path('robots.txt', include('robots.urls')),
        path("__debug__/", include("debug_toolbar.urls")),
        path('summernote/', include('django_summernote.urls')),
    ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models

core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    
    def clean_username(self):
            username = self.cleaned_data.get('username')
            user = User.objects.filter(username=username).exists()
            if user:
                raise ValidationError('This username already exists',code="username_exists")
            return username.strip() 
        
    def clean_email(self):
            email = self.cleaned_data.get('email')
            user = User.objects.filter(email=email).exists()
            if user:
                raise ValidationError('This email already exists',code="email_exists")
            return email.strip() 
      
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        



    

core/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from accounts.forms import RegistrationForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

          
# Create your views here.

class UserLoginView(View):
    form_class = AuthenticationForm
    template_name = 'accounts/login.html'
    
 
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)
        
    def get(self, request):
        global next
        next = request.GET.get('next')
        form = self.form_class
        return render(request,self.template_name,{'form':form})
    
    def post(self, request):
       
        form = self.form_class(request=request,data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])    
            if user is not None:
                login(request, user)
                print('next accounts= ',next )       
                if next:
                    print('next accounts next= ',next )   
                    messages.success(request,f'Hi {user} you are login successfully','success')
                    return redirect(next)
                messages.success(request,f'Hi {user} you are login successfully','success')
                return redirect('/')
                # Redirect to a success page.
            
        else:
            messages.error(request,'username or password is wrong','danger')
      
        return render(request,self.template_name,{'form':form})   
         

class UserLogOut(LoginRequiredMixin, View):
    login_url = 'accounts/login.html'  
    def get(self,request):
        logout(request)
        messages.success(request, 'you are logout successfully.')
        return redirect('/')
        
   

class RegisterView(View):
    form_class = RegistrationForm
    template_name = 'accounts/signup.html'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)
        
    def get(self,request):
        form = self.form_class()
        return render(request,self.template_name,{'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'],cd['email'],cd['password1'])
            #user = authenticate(request, username=cd['username'], password=cd['password1'])
            #user.save()
            #username = request.POST.get("username")
            messages.success(request,'Hi . Your registration was successfully \
                             please login' ,'success')
            #if user is not None:
            #    login(request, user)
            return redirect("accounts:login")
        else:
            messages.error(request,'Please input the correct password','danger')
            
        return render(request,self.template_name,{'form':form})

class UserPasswordResetView(auth_views.PasswordResetView):
	template_name = 'accounts/changepassword.html'
	success_url = reverse_lazy('accounts:password_reset_done')
	email_template_name = 'accounts/password_reset_email.html'
 
class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
	template_name = 'accounts/password_reset_done.html'
 
class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
	template_name = 'accounts/password_reset_confirm.html'
	success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
	template_name = 'accounts/password_reset_complete.html'

core/templates/accounts/changepassword.html
{% extends 'base.html'%}
{% load static %}
{% load compress %}
{% block content%}
<!doctype html>
<html lang="en">
  <head>

  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>
	<body>
        <form class="form-signin" method="post" action=" {% url 'accounts:changepassword' %}">
            {% csrf_token %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Please changepassword </h2>
					{% include 'website/messages.html' %}
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Enter your Email</h3>
						<form action="#" class="login-form">
		      		<div class="form-group">
		      			<input type="text" name="email" class="form-control rounded-left" placeholder="Email" required>
		      		</div>
	            
	            <div class="form-group">
	            	<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Get Started</button>
	            </div>
	          </form>
			  
	        </div>
				</div>
			</div>
		</div>
	</section>

</form>
	</body>
</html>

{% endblock %}

core/templates/accounts/login.html
{% extends 'base.html'%}
{% load compress %}
{% load static %}
{% block content%}
<!doctype html>
<html lang="en">
  <head>

  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>
	<body>
        <form class="form-signin" method="post" action=" {% url 'accounts:login' %}">
			
            {% csrf_token %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Please login </h2>
				
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Have an account?</h3>
						<form action="#" class="login-form">
		      		<div class="form-group">
		      			<input type="text" name="username" class="form-control rounded-left" placeholder="Username or Email" required>
		      		</div>
	            <div class="form-group d-flex">
	              <input type="password" name="password" class="form-control rounded-left" placeholder="Password" required>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
	            		<label class="checkbox-wrap checkbox-primary">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'accounts:changepassword' %}">Forgot Password</a>
								</div>
	            </div>
				<div class="w-50 text-md-right">
				<a href="{% url 'accounts:signup' %}">Signup</a>
							</div>
	            <div class="form-group">
	            	<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Get Started</button>
	            </div>
				
	          </form>
			  
	        </div>
				</div>
			</div>
		</div>
	</section>




</form>
	</body>
</html>

{% endblock %}

core/templates/accounts/messages.html
<p>Your password must contain at least 8 characters.</p>
<p>Your password can’t be entirely numeric.</p>
<p>The correct password is like the pattern below  </p>
<p>123456789ab</p>

core/templates/accounts/password_reset_complete.html
{% extends 'base.html'%}
{% load static %}
{% load compress %}
{% block content%}
<!doctype html>
<html lang="en">
  <head>

  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>
	<body>
        <form class="form-signin" method="post" action=" ">
          
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
         
				
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">   	
						<h3>your password changed.</h3>
            <div class="w-50 text-md-right">
              <a href="{% url 'accounts:login' %}">Log in</a>
            </div>
	        </div>
				</div>
			</div>
		</div>
	</section>

</form>
	</body>
</html>

{% endblock %}

core/templates/accounts/password_reset_confirm.html
{% extends 'base.html'%}
{% load static %}
{% load compress %}
{% block content%}
<!doctype html>
<html lang="en">
  <head>

  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>
	<body>
       
        <form class="form-signin" method="post" action="">
            {% csrf_token %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Please changepassword </h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Enter your new password</h3>
						<form action="#" class="login-form">
							<div class="form-group">
								<input type="password" name="new_password1" class="form-control rounded-left" placeholder="new_password" required>
							</div>
					  <div class="form-group d-flex">
						<input type="password" name="new_password2" class="form-control rounded-left" placeholder="confirm new_password" required>
					  </div>
	            <div class="form-group">
	            	<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Change</button>
	            </div>
	          </form>
          
	        </div>
				</div>
			</div>
		</div>
	</section>

</form>
	</body>
</html>

{% endblock %}

core/templates/accounts/password_reset_done.html
{% extends 'base.html'%}
{% load static %}
{% block content%}
{% load compress %}
<!doctype html>
<html lang="en">
  <head>

  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>
	<body>
        <form class="form-signin" method="post" action=" ">
            {% csrf_token %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
         
				
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">   	
						<h3>we sent you an email.</h3>
	        </div>
				</div>
			</div>
		</div>
	</section>

</form>
	</body>
</html>

{% endblock %}

core/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

core/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

core/templates/accounts/signup.html
{% extends 'base.html'%}
{% load static %}
{% load compress %}
{% block content%}
<!doctype html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Vendor JS Files -->

	</head>
	<body>
        <form class="form-signin" method="post" action=" {% url 'accounts:signup' %}" >
		
            {% csrf_token %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Please Signup </h2>
					{% include 'website/messages.html' %}

				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<div class="icon d-flex align-items-center justify-content-center">
		      		<span class="fa fa-user-o"></span>
		      	</div>
		      	<h3 class="text-center mb-4">Registration Info</h3>
						<form action="#" class="login-form">
					{{form.username.errors}}
		      		<div class="form-group">
		      			<input type="text" name="username" class="form-control rounded-left" placeholder="Username" required>
		      		</div>
					{{form.email.errors}}
	            <div class="form-group d-flex">
	              <input type="email" name="email" class="form-control rounded-left" placeholder="Enter your Email" required>
	            </div>
				<div class="form-group d-flex">
					<input type="password" name="password1" class="form-control rounded-left" placeholder="Password" required>
				  </div>
				  <div class="form-group d-flex">
					<input type="password" name="password2" class="form-control rounded-left" placeholder="Repeat your Password" required>
				  </div>
	           
				  {% include 'accounts/messages.html' %}
	            <div class="form-group">
	            	<button type="submit" class="btn btn-primary rounded submit p-3 px-5">Get Started</button>
	          
	          </form>
	        </div>
				</div>
			</div>
		</div>
	</section>
	




</form>
	</body>


</html>

{% endblock %}