core/blog/urls.py
from django.urls import path
from blog.views import * 
from django.contrib.sitemaps.views import sitemap
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('',blog_view, name ='blog'),
    path('post-<int:post_id>/<slug:post_slug>/',Blog_Details_View.as_view(), name ='blog-details'),
    path('category/<str:cat_name>/',blog_view, name ='category'),
    path('tag/<str:tag_name>/',blog_view, name ='tag'),
    path('author/<str:author_username>/',blog_view,name ='author'),
    path('search/',Searchview.as_view(),name ='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('like/',LikePost_View, name ='like'),
    ]
 

core/mysite/urls.py
from django.contrib import admin 
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}
     
urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('website.urls')),
        path('blog/',include('blog.urls')),  
        path('captcha/', include('captcha.urls')),
        path('accounts/',include('accounts.urls')),
        path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
        path('robots.txt', include('robots.urls')),
        path("__debug__/", include("debug_toolbar.urls")),
        path('summernote/', include('django_summernote.urls')),
    ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from io import BytesIO
from django.core.files import File
from taggit.managers import TaggableManager
from mysite.tools import UploadToPathAndRename
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils.text import slugify

def get_image_field(self):
    output = []
    for k, v in self.__dict__.items():
        if isinstance(v, ImageFieldFile):
            output.append(k)
    return output


class MainModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name=_("create date"))
    modify_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name=_("modify date"))
    is_active = models.BooleanField(default=True, verbose_name=_("is active"))

    def save(self, *args, **kwargs):
        image_fields = get_image_field(self)
        if image_fields:
            for i in image_fields:
                if hasattr(self, i) and isinstance(getattr(self, i), ImageFieldFile):
                    image = Image.open(getattr(self, i).file)
                    image_io = BytesIO()
                    image_extension = getattr(self, i).name.rpartition(".")[-1].upper()
                    image_extension = "JPEG" if image_extension == "JPG" else image_extension
                    image.save(image_io, image_extension, quality=60)
                    new_image = File(image_io, name=getattr(self, i).name)
                    setattr(self, i, new_image)
        self.full_clean()
        super().save(*args, **kwargs)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
# Create your models here.

class Post(MainModel): 
    image = models.ImageField(upload_to=UploadToPathAndRename("blog"),default='blog/defualt.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True, related_name='posts_author')
    title = models.CharField(max_length=255)
    slug = models.SlugField(null=True,blank=True,unique=True)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    login_require = models.BooleanField(default=False)
    
    def save (self, force_insert = False, force_update=False, using=None,update_fields=None):
        self.slug = slugify(self.title)
        super(Post,self).save()
        
    def image_tag(self):
        return mark_safe(f'<img src="{settings.MEDIA_URL}{self.image}" height="50" />')
    image_tag.allow_tags = True
    image_tag.short_description = "---"
    
    def get_absolute_url(self):
       return reverse("blog:blog-details", args=(self.id, self.slug))
    def __str__(self):
        return self.title
    
    def like_count(self):
        return self.upost.count()
   
    def user_can_like(self, user):
        user_like = user.uvote.filter(post = self)
        if user_like.exists():
            return True
        return False
    
class Comment(MainModel):
    post = models.ForeignKey(Post,on_delete = models.CASCADE, related_name="comments",null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments",null=True,blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name="replies",null=True,blank=True)
    message = models.TextField()
    approach = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True) 
    class Meta:
        ordering = ('created_date',)
  
    def __str__(self):
        return self.message[:20]
    
class VoteUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='upost')
    
    def __str__(self):
        return f'{self.user} --> like this post-->  {self.post.slug}' 
    
class PostImage(models.Model):
    product = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=UploadToPathAndRename("blog"),default='blog/defualt.jpg')

    def __unicode__(self):
        return self.product.title

    def __str__(self):
        return self.product.title

  

core/blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm): 
    captcha = CaptchaField() 
    class Meta:
        model = Comment
        fields = ['message',]

core/blog/views.py
from typing import Any
from django import http
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post,PostImage
from django.utils import timezone
from blog.forms import  CommentForm
from blog.models import Post,Comment,VoteUser
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from taggit.models import Tag
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def blog_view(request,**kwargs):
    posts = Post.objects.filter(status=1,published_date__lte = timezone.now())
    if kwargs.get('cat_name') != None:
        cat = kwargs.get('cat_name')
        posts = posts.filter(category__name = cat.replace("-", " "))
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__slug__in = [kwargs['tag_name']])
        
    posts = Paginator(posts,2)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    tags = Tag.objects.all()
    context = {'posts':posts,'tags':tags} 
    return render (request , 'blog/blog-home.html',context)

def LikePost_View(request):
    post_id = request.GET['post_id']
    post = get_object_or_404(Post, id = post_id)
    like = VoteUser.objects.filter(post= post, user= request.user)
    data = ("item successfully added to cart")
    if like.exists():
        like.delete()
        post.save()
        return JsonResponse({"error": data})
    else:
        VoteUser.objects.create(post= post,  user= request.user)           
        return JsonResponse({"success": data})
        

class Blog_Details_View(View):
    form_class = CommentForm
    template_name = 'blog/blog-details.html'
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,pk=kwargs['post_id'],slug= kwargs['post_slug'])
        self.images_instance = PostImage.objects.filter(product_id =kwargs['post_id'])
        self.comment_instance = Comment.objects.filter(approach=True,parent=None,post=self.post_instance.id).order_by('created_date')        
        #self.reply_instance = Comment.objects.filter(approach=True,parent__isnull=False,post=self.post_instance.id).order_by('created_date')        
        return super().setup(request, *args, **kwargs)
    def get(self,request,*args, **kwargs):
        form = self.form_class()
        if not self.post_instance.login_require or request.user.is_authenticated:
            print('salaam')
            can_like = False
            if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
                can_like = True
            self.post_instance.counted_views+=1
            self.post_instance.save()
            form = self.form_class()
            content = {'post':self.post_instance,'form':form,'can_like':can_like,'images':self.images_instance,'comments': self.comment_instance}#,"replyes":self.reply_inctance,
            return render (request , self.template_name,content)
        else:
            return redirect("/accounts/login?next="+request.path)
    def post(self,request,*args, **kwargs):
        parent_id = request.POST.get('parent_id')
        form = self.form_class(request.POST)        
        if form.is_valid():
            endcomment = form.save(commit=False)
            endcomment.post = self.post_instance
            if request.user.is_authenticated:
                endcomment.user = request.user
            else:
                endcomment.user = None
            endcomment.parent_id = parent_id
            endcomment.save()
            if parent_id:
                messages.success(request,'Thanks . Your Reply has been received.','success')
            else:
                messages.success(request,'Thanks . Your comment has been received.','success')
        else:
            messages.error(request,'Please inter correct pattern .','error')
        return redirect('blog:blog-details', self.post_instance.id, self.post_instance.slug) 
      


class Searchview(View):
    def get(self,request):
        posts = Post.objects.filter(status=1)
        q = request.GET.get('q')
        posts = posts.filter(content__icontains=q)
        posts = Paginator(posts,2)
        try:
            page_number = request.GET.get('page')
            posts = posts.get_page(page_number)
        except PageNotAnInteger:
            posts = posts.get_page(1)
        except EmptyPage:
            posts = posts.get_page(1)
        context = {'posts':posts}
        return render (request , 'blog/blog-home.html',context)



        

core/templates/blog/blog-all-tags.html
{% load static %}
<div class="col-lg-12">
    <div class="sidebar-item tags">
      <div class="sidebar-heading">
        <h2>Tag Clouds</h2>
      </div>
      <div class="content">
        <ul>
            {% for tag in tags %}
          <li><a href="{% url 'blog:tag' tag_name=tag.slug %}">{{tag.name}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

core/templates/blog/blog-categories.html
{% load static %}
  <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    {% for cat in post.category.all %}
                    <div class="content">
                      <ul>
                        <li><a href="{% url 'blog:category' cat_name=cat.name|slugify %}">{{ cat.name }} </a>{% if not forloop.last %},{% endif%}</a></li>                  
                      </ul>
                    </div>
                    {% endfor %}
                  </div>
                </div>

core/templates/blog/blog-comment.html
{% load static %}
<div class="col-lg-12">
  <div class="sidebar-item comments">
    <div class="sidebar-heading">
      <h2>{{ comments | length }} comments</h2>
    </div>
    <div class="content">
      <ul>
         {% for comment  in comments %}{% if comment.parent == None %}
        <li>
          <div class="author-thumb">
            <img src="{% static 'blog/assets/images/comment-author-01.jpg' %}" alt="">
          </div>
          <div class="right-content">
           <h4>{{comment.user}}<span>{{comment.created_date| timesince}}</span></h4>
            <p>  {{comment.message}} .</p>
             <button onclick="set_value({{comment.id}})" class="btn btn-primary">Reply</button>
          </div>
        </li>
         {% for reply in comment.replies.all %}{% if reply.approach %}
        <li class="replied">
          <div class="author-thumb">
       <img src="{% static 'blog/assets/images/comment-author-02.jpg' %}" alt="">
          </div>
        <div class="right-content">
         <h4>{{reply.user}}<span>{{reply.created_date| timesince}}</span></h4>
          <p>{{reply.message}}.</p>
          </div>
        </li>
         <li>
        {%endif%}{% endfor %}
         {%endif%}{% endfor %}
      </ul>
      
    </div>
  </div>
</div>

core/templates/blog/blog-details.html
{% extends 'base_blog.html'%}
{% load humanize %}
{% load static %}
{% block content%}
{% load blog_tags %}
{% load social_share %}

    <title>Stand Blog - Post Details</title>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Post Details</h4>
                <h2>Single blog post</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      
                      <a><h4>Aenean pulvinar gravida sem nec</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                        <li><a>{{post.published_date|date:"d M Y"}}</a></li>
                        <li><a>{{post.counted_views|intcomma}} Views</a></li>
                        <li><a>{{ comment | length }} Comments</a></li>
                        <li><a id="count1">{{post.upost.all.count}} </a> <a>Like</a> </li>
                      </ul>
                      {{ post.content|safe}}
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                            
                              {% if request.user.is_authenticated and not can_like  %}
                              <li>
                                <a>
                                  <i style="font-size: 20px;" id="like" class="likebutton fa fa-heart-o" data-catid="{{ post.id }}"></i>
                                  <span id="count">{{post.upost.all.count}}</span> Like
                                </a>
                              </li>
                              
                              {% elif request.user.is_authenticated and  can_like  %}
                              <li>
                                <a>
                                  <i style="font-size: 20px;" id="like" class="likebutton fa fa-heart" data-catid="{{ post.id }}"></i>
                                  <span id="count">{{post.upost.all.count}}</span> Like
                                </a>
                              </li>
                              {% endif %}
                              

                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                                  <li><i class="fa fa-share-alt"></i></li>
                                  <li>{% post_to_whatsapp post.get_absolute_url "WhatsApp" %}</li>,
                                   <li> {% post_to_telegram "New Post: {{post.title}}" post.get_absolute_url %}</li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      
                      {% include 'blog/blog-comment.html' %}
           
    
                 
                <div class="col-lg-12" id = "message">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading" >
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form  action="{{ post.get_absolute_url }}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="parent_id" id="parent_id" value="">
                        <div class="row">
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message"   id="textarea" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">{{form.captcha}}</div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit"  class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">

                  {% include 'blog/blog-search.html' %}
                  
                </div>
                {% populare_posts %}
							
							
								{% recent_posts %}

                {% include 'blog/blog-categories.html' %}
                
                {% include 'blog/blog-tags.html' %}		

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script>
    function set_value(id){
      document.getElementById('parent_id').value = id;
      window.location.href = '#message'
      const textarea = document.getElementById("textarea").placeholder = "Type your reply";

    }
  </script>

    {% endblock %}

core/templates/blog/blog-home.html
{% extends 'base_blog.html'%}
{% load humanize %}
{% load static %}
{% block content%}
{% load blog_tags %}


    <title>Stand Blog Posts</title>




    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Recent Posts</h4>
                <h2>Our Recent Blog Entries</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              
              <div class="row">
                {% for post in posts %}
                <div class="col-lg-6">
                  
                  <div class="blog-post">
                    <div class="blog-thumb">
                    
                      <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }} " alt=""></a>
                    </div>
                    <div class="down-content">
                      
                      <a href="{{ post.get_absolute_url }}"><h4>{{post.title}}</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url 'blog:author' author_username=post.author.username%}">{{post.author.get_full_name}}</a></li>
                        <li><a>{{post.published_date|naturalday}}</a></li>
                        <li><a>{{post.counted_views}} Views</a></li>
                        <li><a>{% comments_count post.id %} Comments</a></li>
                        <li><a>{% likes_count post.id %} Like</a></li>
                      </ul>
                      <a href="{{ post.get_absolute_url }}">{{ post.content|truncatewords:15|safe}}</a>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a>Best Templates</a>,</li>
                              <li><a>TemplateMo</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>                
                </div>
                {% endfor%}


                <div class="col-lg-12">
                  <ul class="page-numbers">
                    {% if posts.has_previous %}
                    <li class="page-item">
                      <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}" class="page-link" aria-label="Previous">
                        <span aria-hidden="true">
                          <span class="fa fa-angle-double-left"></span>
                        </span>
                      </a>
                    </li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                    <li class="page-item active"><a href="?page={{i}}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}" class="page-link">{{i}}</a></li>
                    {% else %}
                    <li class="page-item "><a href="?page={{i}}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}" class="page-link">{{i}}</a></li>
                    {% endif %}
                    {% endfor%}
							    	{% if posts.has_next %}
                    <li class="page-item">
                      <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}" class="page-link" aria-label="Next">
                        <span aria-hidden="true">
                          <span class="fa fa-angle-double-right"></span>
                        </span>
                      </a>
                    </li>
             
                      {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">

                  {% include 'blog/blog-search.html' %}	
                </div>

                {% populare_posts %}
							
							
								{% recent_posts %}

                {% categories_posts %}
     
                {% include 'blog/blog-all-tags.html' %}	
                


              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    
    {% endblock %}


 

core/templates/blog/blog-search.html
{% load static %}
<div class="sidebar-item search">
    <form id="search_form" name="gs" method="GET" action="{% url 'blog:search' %}">
      <input type="text" name="q" class="searchText" placeholder="{% if request.GET.q %}{{request.GET.q}}{%else%}type to search...{% endif %}" autocomplete="on">
      
    </form>
  </div>

core/templates/blog/blog-tags.html
{% load static %}
<div class="col-lg-12">
    <div class="sidebar-item tags">
      <div class="sidebar-heading">
        <h2>Tag Clouds</h2>
      </div>
      <div class="content">
        <ul>
            {% for tag in post.tags.all %}
          <li><a href="{% url 'blog:tag' tag_name=tag.slug %}">{{tag.name}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

core/templates/blog/categories_posts.html
  {% load static %}
  <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    {% for name,count in cat_dict.items %}
                    <div class="content">
                      <ul>
                        <li><a href="{% url 'blog:category' cat_name=name|slugify %}">- {{ name }}  ----- {{count}} </a></li>
                      </ul>
                    </div>
                    {% endfor %}
                  </div>
                </div>

core/templates/blog/populare-posts.html
{% load static %}
{% load humanize %}
<div class="col-lg-12">
    <div class="sidebar-item recent-posts">
      <div class="sidebar-heading">
        <h2>Populare Posts</h2>
      </div>
      <div class="content">
        <ul>
            {% for post in posts %}
            <div class="thumb">
               <!-- <img class="img-fluid" src="{{post.image.url}}" width="80px" height="200px"   alt="">-->
              </div>
          <li><a href="{{ post.get_absolute_url }}">
            <h6>{{post.title}}</h6>
            <span>{{post.counted_views}} views</span>
          </a></li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>

core/templates/blog/recent-posts.html
{% load static %}
{% load humanize %}
<div class="col-lg-12">
    <div class="sidebar-item recent-posts">
      <div class="sidebar-heading">
        <h2>Recent Posts</h2>
      </div>
      <div class="content">
        <ul>
            {% for post in posts %}
            <div class="thumb">
              <!--<img class="img-fluid" src="{{post.image.url}}" width="80px" height="200px"   alt=""> -->
              </div>
          <li><a href="{{ post.get_absolute_url }}">
            <h6>{{post.title}}</h6>
            <span>{{post.published_date|naturalday}}</span>
          </a></li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>