core/accounts/urls.py
from django.urls import path
#from accounts.views import *
from accounts.views import * 


app_name = 'accounts'

urlpatterns = [
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogOut.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='signup'),
    path('changepassword/',UserPasswordResetView.as_view(),name='changepassword'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

core/blog/urls.py
from django.urls import path
from blog.views import * 
from django.contrib.sitemaps.views import sitemap
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('',blog_view, name ='blog'),
    path('post-<int:post_id>/<slug:post_slug>/',Blog_Details_View.as_view(), name ='blog-details'),
    path('category/<str:cat_name>/',blog_view, name ='category'),
    path('tag/<str:tag_name>/',blog_view, name ='tag'),
    path('author/<str:author_username>/',blog_view,name ='author'),
    path('search/',Searchview.as_view(),name ='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('like/',LikePost_View, name ='like'),
    ]
 

core/mysite/urls.py
from django.contrib import admin 
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}
     
urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('website.urls')),
        path('blog/',include('blog.urls')),  
        path('captcha/', include('captcha.urls')),
        path('accounts/',include('accounts.urls')),
        path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
        path('robots.txt', include('robots.urls')),
        path("__debug__/", include("debug_toolbar.urls")),
        path('summernote/', include('django_summernote.urls')),
    ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('resume', resume_view, name='resume'),
    path('skill', skill_view, name='skill'),
    path('', coming_view, name='coming'),
    ]

core/website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from io import BytesIO
from django.core.files import File
from mysite.tools import UploadToPathAndRename
from datetime import date


class MainModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name=_("create date"))
    modify_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name=_("modify date"))
    is_active = models.BooleanField(default=True, verbose_name=_("is active"))

    def get_image_fields(self):
        return [k for k, v in self.__dict__.items() if isinstance(v, ImageFieldFile)]

    def save(self, *args, **kwargs):
        image_fields = self.get_image_fields()
        if image_fields:
            for field_name in image_fields:
                image_field = getattr(self, field_name)
                if isinstance(image_field, ImageFieldFile) and image_field:
                    image = Image.open(image_field.file)
                    image_io = BytesIO()
                    image_extension = image_field.name.rpartition(".")[-1].upper()
                    image_extension = "JPEG" if image_extension == "JPG" else image_extension
                    image.save(image_io, image_extension, quality=60)
                    new_image = File(image_io, name=image_field.name)
                    setattr(self, field_name, new_image)
        self.full_clean()
        super().save(*args, **kwargs)

    class Meta:
        abstract = True


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True, default="No Subject")
    message = models.TextField(default="No message provided")

    def __str__(self):
        return self.name


class Information(MainModel):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to=UploadToPathAndRename("website"), default='website/default.jpg')
    job = models.CharField(max_length=100, default="Unemployed")
    title = models.CharField(max_length=100, default="Untitled")
    address = models.CharField(max_length=100, default="Not specified")
    city = models.CharField(max_length=30, default="Not specified")
    phone = models.CharField(max_length=15, default="Not specified")
    email = models.EmailField(default="example@example.com")
    git = models.CharField(max_length=100, default="Not specified")
    whatsapp = models.CharField(max_length=100, default="Not specified")
    telegram = models.CharField(max_length=100, default="Not specified")
    instagram = models.CharField(max_length=100, default="Not specified")
    linkedin = models.CharField(max_length=100, null=True, default="Not specified")
    website = models.CharField(max_length=100, default="Not specified")
    birthday = models.DateField(default=date(2000, 1, 1))
    degree = models.CharField(max_length=50, default="Not specified")
    freelance = models.CharField(max_length=50, default="Not specified")
    about_me = models.TextField(default="Not provided")
    about_my_resume = models.TextField(null=True, default="Not provided")
    my_works = models.CharField(max_length=255, null=True, default="No works listed")

    def __str__(self):
        return str(self.author)


class Education(MainModel):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default="Untitled")
    education = models.CharField(max_length=100, default="Not specified")
    year = models.CharField(max_length=100, default="Not specified")
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.author)


class ProfessionalExperience(MainModel):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default="Untitled")
    education = models.CharField(max_length=100, default="Not specified")
    year = models.CharField(max_length=100, default="Not specified")
    message = models.TextField(default="No message provided")
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.author)


class Skill(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.TextField(default="Untitled Skill")

    def __str__(self):
        return str(self.author)


class MySkill(models.Model):
    skill_category = models.ForeignKey(Skill, on_delete=models.SET_NULL, null=True)
    skill = models.CharField(max_length=20, default="Untitled Skill")
    percent = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.skill_category)


class UserImage(MainModel):
    information = models.ForeignKey(Information, on_delete=models.CASCADE)
    image_more = models.ImageField(upload_to=UploadToPathAndRename("website"), default='website/default.jpg')


class NewsLetter(models.Model):
    email = models.EmailField(default="example@example.com")

    def __str__(self):
        return self.email

core/website/forms.py
from django import forms
from website.models import Contact,NewsLetter
from captcha.fields import CaptchaField



class ContactForm(forms.ModelForm):
    captcha = CaptchaField() 
    class Meta:
        model = Contact
        fields = '__all__'


class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = '__all__'
        

core/website/views.py
from django.shortcuts import render
from .forms import ContactForm, NewsLetterForm
from django.contrib import messages
from .models import MySkill, Skill, UserImage, ProfessionalExperience, Education


def index_view(request):
    return render(request, 'website/index.html')


def about_view(request):
    img = UserImage.objects.all().first()
    context = {'img': img}
    return render(request, 'website/about.html', context)


def resume_view(request):
    profess = ProfessionalExperience.objects.filter(status=1)
    educate = Education.objects.filter(status=1)
    context = {'profess':profess,'educate':educate}
    return render(request ,'website/Resume.html',context)


def skill_view(request):
    info = Skill.objects.all().first()
    skills = MySkill.objects.all()
    context = {'skills': skills, 'info': info}
    return render(request, 'website/skill.html', context)


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thanks . Your message has been received.', 'success')
        else:
            messages.error(request, 'Please inter correct pattern .', 'error')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'website/contact.html', context)


def coming_view(request):
    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thanks . Your message has been received.', 'success')
        else:
            messages.error(request, 'Please inter correct pattern .', 'error')
    form = NewsLetterForm()
    context = {"form": form}
    return render(request, 'website/coming_soon/index.html',context)

core/templates/website/includes/footer.html
{% load static %}
<footer id="footer" style="background-color: gainsboro">
    <div class="container">
      <h3>Reza Latifi</h3>
      <p>Don’t wait for extraordinary opportunities. Seize common occasions and make them great..</p>
      <div class="social-links">
        <a href="{{ myinformations.whatsapp }}"  class="whatsapp"><i class="bi bi-whatsapp"></i></a>
        <a href="{{ myinformations.telegram }}" class="telegram"><i class="bi bi-telegram"></i></a>
        <a href="{{ myinformations.instagram }}" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="mailto:{{ myinformations.email }}" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="{{ myinformations.linkedin }}"class="linkedin"><i class="bx bxl-linkedin"></i></a>
        <a href="{{ myinformations.git }}" class="git"><i class="bi bi-github"></i></a>
    
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: [license-url] -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

core/templates/website/includes/footer_references.html
{% load static %}
{% load compress %}
  <!-- Vendor JS Files -->
  
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
  {% compress js %}
  <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'website/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'website/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'website/vendor/typed.js/typed.umd.js' %}"></script>
  <script src="{% static 'website/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'website/js/toastr.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'website/js/toastr.min.js' %}"></script>  
  <script src="{% static 'website/js/main.js' %}"></script>
  <script src="{% static 'login/js/jquery.min.js' %}"></script>
  <script src="{% static 'login/js/popper.js' %}"></script>
  <script src="{% static 'login/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'login/js/main.js' %}"></script>
	<script type="text/javascript" src="{% static 'login/js/toastr.min.js' %}"></script>  
  {% endcompress %}
  
  <script>
  {% if messages %}
  document.addEventListener("DOMContentLoaded", function(event) {
      toastr.options = { "closeButton": true, "debug": false, "newestOnTop": true,
          "progressBar": false, "positionClass": "toast-top-right", "preventDuplicates": true,
          "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000",
          "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear",
          "showMethod": "fadeIn", "hideMethod": "fadeOut" };
      {% autoescape off %}
          {% for msg in messages %}
              toastr.{{ msg.level_tag }}("{{ msg }}");
          {% endfor %}
      {% endautoescape %}
  });
{% endif %}
</script>

  <!-- Template Main JS File -->

  <script>
    $(function() {

      // Add refresh button after field (this can be done in the template as well)
      $('img.captcha').after(
              $('<a href="#void" class="captcha-refresh" > <i class="fa fa-refresh" style="font-size:24px"></i> </a>')
              );
  
      // Click-handler for the refresh-link
      $('.captcha-refresh').click(function(){
          var $form = $(this).parents('form');
          var url = location.protocol + "//" + window.location.hostname + ":"
                    + location.port + "/captcha/refresh/";
  
          // Make the AJAX-call
          $.getJSON(url, {}, function(json) {
              $form.find('input[name="captcha_0"]').val(json.key);
              $form.find('img.captcha').attr('src', json.image_url);
          });
  
          return false;
      });

});

  </script>

core/templates/website/includes/head_references.html
{% load static %}
{% load compress %}


<link href="{% static 'assets/base/favicon.png' %} " rel="icon">
<link href="{% static 'assets/base/apple-touch-icon.png' %} " rel="apple-touch-icon">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
<!-- Vendor CSS Files -->
{% compress css %}
<link href="{% static 'website/vendor/aos/aos.css' %} " rel="stylesheet">
<link href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
<link href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
<link href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %} " rel="stylesheet">
<link href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %} " rel="stylesheet">
<link href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %} " rel="stylesheet">
<link href="{% static 'website/css/toastr.min.css' %}" rel="stylesheet">
<!-- Template login CSS File -->
<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
<link href="{% static 'login/css/toastr.min.css' %}" rel="stylesheet">
<!-- Template Main CSS File -->
<link href="{% static 'website/css/style.css' %} " rel="stylesheet">
{% endcompress %}

core/templates/website/includes/header.html
{% load static %}
<header id="header" class="d-flex flex-column justify-content-center">
     <nav id="navbar" class="navbar nav-menu">
      <ul>
        <li><a href="{% url 'website:index'%}"><i class="bx bx-home djdt-active"></i> <span>Home</span></a></li>
        <li><a href="{% url 'website:about'%}"><i class="bx bx-clipboard"></i> <span>About</span></a></li>
        <li><a href="{% url 'website:resume'%}"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
        <li><a href="{% url 'website:skill'%}"><i class="bx bx-server"></i> <span>Skills</span></a></li>
        <li><a href="{% url 'website:contact'%}"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'accounts:logout' %}"><i class="bx bx-user"></i> <span>Logout</span></a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}"><i class="bx bx-user"></i> <span>Login</span></a></li>
        {% endif %}
        <li><a href="{% url 'blog:blog'%}"><i class="bx bx-book-content"></i> <span>blog</span></a></li>
      </ul>
    </nav><!-- .nav-menu -->
  </header><!-- End Header -->
  